name: Infracost
description: Show cloud cost estimate changes for Terraform in pull requests.
author: infracost
branding:
  icon: trending-up
  color: yellow
inputs:
  path:
    description: Path to the Terraform directory or JSON/plan file. Either `path` or `config_file` is required.
    required: false
  terraform_plan_flags:
    description: Flags to pass to the 'terraform plan' command, e.g. `"-var-file=my.tfvars -var-file=other.tfvars"`. Applicable when path is a Terraform directory.
    required: false
  terraform_workspace:
    description: The Terraform workspace to use. Applicable when path is a Terraform directory. Only set this for multi-workspace deployments, otherwise it might result in the Terraform error "workspaces not supported".
    required: false 
  usage_file:
    description: Path to Infracost usage file (https://www.infracost.io/docs/usage_based_resources) that specifies values for usage-based resources, see https://github.com/infracost/infracost/blob/master/infracost-usage-example.yml for the available options.
    required: false
  config_file:
    description: If your repo has multiple Terraform projects or workspaces, define them in a config file (https://www.infracost.io/docs/config_file/) and set this input to its path. Their results will be combined into the same diff output. Cannot be used with path, terraform_plan_flags or usage_file inputs. 
    required: false
  percentage_threshold:
    description: (percentage_threshold is deprecated, use post_condition instead) The absolute percentage threshold that triggers a pull request comment with the diff. Defaults to 0, meaning that a comment is posted if the cost estimate changes. For example, set to 5 to post a comment if the cost estimate changes by more than plus or minus 5%.
    required: false
  post_condition:
    description: |
      A JSON string describing the condition that triggers pull request comments, can be one of these:
      - `'{"has_diff": true}'`: only post a comment if there is a diff. This is the default behavior.
      - `'{"always": true}'`: always post a comment.
      - `'{"percentage_threshold": 0}'`: absolute percentage threshold that triggers a comment. For example, set to 1 to post a comment if the cost estimate changes by more than plus or minus 1%.
    required: false
    default: '{"has_diff": true}'
outputs:
  total_monthly_cost:
    description: The new total monthly cost estimate.
  past_total_monthly_cost:
    description: The past total monthly cost estimate.
runs:
  using: docker
  image: docker://infracost/infracost:latest # Use a specific version instead of latest if locking is preferred
  args:
    - ${{ inputs.path }}
    - ${{ inputs.terraform_plan_flags }}
    - ${{ inputs.terraform_workspace }}
    - ${{ inputs.usage_file }}
    - ${{ inputs.config_file }}
    - ${{ inputs.percentage_threshold }}
    - ${{ inputs.post_condition }}
